### ISSUE TITLE
Gather some images for the database seeds

### ISSUE THREAD

**Issue by brianlens** [brianlens/Stutor#2]
Just anything that looks good. Make it 10.

**Comment by pacmessica** [comment]
I'm on it!

**Comment by pacmessica** [comment]
https://upload.wikimedia.org/wikipedia/en/7/70/Shawn_Tok_Profile.jpg
https://lh3.googleusercontent.com/-ZadaXoUTBfs/AAAAAAAAAAI/AAAAAAAAAAA/3rh5IMTHOzg/photo.jpg
https://upload.wikimedia.org/wikipedia/commons/2/2c/Juliana_Bastos_Marques_profile_pic.jpg
https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTwzq_DNAdlNJA4uS4ZelE2F5n6SQGhJLSkwEOrDZk2Nwb0ElzX
https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQB5rnQyrcAbqdTCotb4zqyQZvsoRAaBZT91KjSuTt6kbPRkR2s
http://lit.mit.edu/wp-content/uploads/ebrinkema-profile.jpg
http://ss-medicinska-ri.skole.hr/upload/ss-medicinska-ri/album/389/large_img_499885.jpg
https://upload.wikimedia.org/wikipedia/commons/5/59/Sivan_shavit_profile.jpg
http://www.odilederousiers.fr/charles/dl/profile.png
http://orig08.deviantart.net/120d/f/2012/201/8/a/profile_picture_by_leochemaxp-d57xmql.jpg
