### ISSUE TITLE
Create a seeds file for 10 listings

### ISSUE THREAD

**Issue by brianlens** [brianlens/Stutor#3]
you can use the images from #2
[] upload all seeds into seeds.rb and push to master

**Comment by pacmessica** [comment]
see images in #2

**Comment by pacmessica** [comment]
I'm going to create a seed template now

**Comment by pacmessica** [comment]
empty seed template- fill in between "" and post back into this thread

Tutor.create( {name: "", gpa: "", subject: "", postal_code: "", email: "", phone_number: "", images: "", description:"", social_links: "", price: "" })

**Comment by jakeprins** [comment]
Tutor.create( {name: "Jeff Green", gpa: "7.4", subject: "History", postal_code: "2202SR", email: "Jeff_Green@veryhotmail.com", phone_number: "0620984649", images: "https://pbs.twimg.com/profile_images/559752051819692032/aSogDYZe.jpeg", description:"I've been working as a teacher for almost 15 years. I'm specialized in history but also for math problems I can most likely help you with a lot. I am mostly available in the evening. ", social_links: "www.linkedin.com/Jeff", price: "25" })

Tutor.create( {name: "Barack Obama", gpa: "9.0", subject: "Politics/History", postal_code: "3452AR", email: "Baraka_Waka_Flame@dopehood.com", phone_number: "061194563", images: "https://pbs.twimg.com/profile_images/1645586305/photo.JPG", description:"I have almost 8 years experience as the president of a very shitty country, so I know how to solve problems, or at least try to. If you have troubles learning about politics, or want some advice on how to get into politics, please contact me.", social_links: "www.linkedin.com/BarackaBam", price: "85" })

Tutor.create( {name: "Wouter de Vos", gpa: "8.3", subject: "Programming", postal_code: "4040As", email: "foxy_coder@bootcamp.com", phone_number: "0691129112", images: "https://pbs.twimg.com/profile_images/674939894024794112/WMeJynkt.jpg", description:"Having troubles with your code? Just let me fix it. I will debug the hell out of your program.", social_links: "www.linkedin.com/foxycoder", price: "60" })

**Comment by brianlens** [comment]
Tutor.create( {name: "Brian Lens", 
gpa: "8.0", 
subject: "Mathematics", 
postal_code: "1092VC", 
email: "brian@stutor.nl", 
phone_number: "+31 6 46396642",
images: "https://media.licdn.com/media/p/5/005/0a0/1aa/0df94d2.jpg", 
description:"Hi, I'm Brian and I was very proficient in Maths during secondary school. I'm looking for students who have a hard time with calculus, integrals and de-linear malfunctiation", 
social_links: "https://nl.linkedin.com/in/brian-lens-70887750", 
price: "27.5" })

Tutor.create( {name: "Adri Rietjens", 
gpa: "8.5", 
subject: "Physics", 
postal_code: "1075AB", 
email: "a3@gmail.com", 
phone_number: "+31 6 57889301",
images:"https://media.licdn.com/media/AAEAAQAAAAAAAAIuAAAAJDRkZDc3ZmQ2LWNjZTktNDg5Zi1iMWQ2LTI5MTQwNGE2YTRjNA.jpg",
description:"Hi there, I'm Adri and very keen on Physics, if you need any help I can show you wonderful world of physics. I have an extensive command of it, from electric circuits to quantum physics", social_links: "https://www.linkedin.com/uas/login?trk=D8E90337EA&session_redirect=https%3A%2F%2Fwww.linkedin.com%2Fin%2Farietjens%2Fnl", 
price: "30" })

Tutor.create( {name: "Pim Muns",
gpa: "6.5", 
subject: "German",
postal_code: "1095AW",
email: "p.b.muns@gmail.com",
phone_number: "+31 6 11738527",
images:"https://media.licdn.com/media/AAEAAQAAAAAAAALaAAAAJDBmZTljNjkzLWQzZmItNGMzZi04ZjUxLWUwN2EyODRjMTNhZA.jpg",
description:"Hello! My name is Pim and I'm from Geleen, but live in Amsterdam now. When I studied at my secondary school in Geleen I was very good in German, that's why I want to learn it to you now!", social_links: "https://www.linkedin.com/in/pimmuns", 
price: "25" })

**Comment by pacmessica** [comment]
Tutor.create( {name: "Robert Boemke", gpa: "3.8", subject: "English", postal_code: "1012 LB", email: "r.boemke@gmail.com", phone_number: "043 - 388 52 82", images: "http://www.odilederousiers.fr/charles/dl/profile.png", description:"I am currently doing my masters in English Literature at the University of Amsterdam. I completed my undergraduate degree at Columbia University in Psychology and Gender Studies.", social_links: "https://www.linkedin.com/in/robert", price: "20" })

Tutor.create( {name: "Edward Sharpe", gpa: "4.0", subject: "Computer Science", postal_code: "1012 LB", email: "e.sharpe@gmail.com", phone_number: "043 - 366 52 87", images: "https://avatars1.githubusercontent.com/u/80280?v=3&s=460", description:"I have a Bachelor's Degree in Math and Computer Science from McGill University in Montreal. I am currently doing a Master's in Computer Science at the University of Amsterdam.", social_links: "https://www.linkedin.com/in/robert", price: "25" })

**Comment by brianlens** [comment]
Tutor.create( {name: "Bas Joosten", 
gpa: "10.0", 
subject: "Economics", 
postal_code: "1079AG", 
email: "bas.joosten@bcg.nl", 
phone_number: "+31 6 57878241",
images: "https://media.licdn.com/media/p/6/005/075/0be/11b6f9b.jpg", 
description:"Hi, I'm Bas and I was very proficient in Economics during secondary school and my University grade at Cambridge. If you wan to get it right you should hire me!", 
social_links: "https://nl.linkedin.com/in/bas-joosten-800aa938/nl", 
price: "47.5" })

**Comment by ReneeVL85** [comment]
Tutor.create( {name: "Mark Rutte", gpa: "8.5", subject: "English", 
postal_code: "2514CD", email: "markrutte@primeminister.nl", phone_number: "0612345789", images: "http://www.gewoon-nieuws.nl/wp-content/uploads/2013/03/mark-rutte3.jpg", description:"Hi I am Mark and I run the Netherlands but I have to speak English all the time so I would like to teach you some!", 
social_links: "https://www.linkedin.com/markrutte", price: "25" })

Tutor.create( {name: "Willem-Alexander van Buuren", gpa: "7.5", subject: "History", 
postal_code: "12514CC", email: "renee.v.leijen@gmail.com", phone_number: "0617612365", images: "http://www.tramharmonie.nl/wp-content/uploads/willem-alexander.jpg", description:"Hi I am the king of the Netherlands and I like to share my knowledge of the worlds History ", 
social_links: "https://www.linkedin.com/wavanbuuren", price: "25" })
